# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-31 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QandAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128, unique=True)),
                ('answer', models.CharField(max_length=128)),
                ('header', models.CharField(max_length=128)),
            ],
        ),
    ]
